abort cutting release if there are no commits
Signed-off-by: Max Eshleman <meshleman@pivotal.io>

diff --git a/tasks/create-final-release/backport/task b/tasks/create-final-release/backport/task
--- a/tasks/create-final-release/backport/task
+++ b/tasks/create-final-release/backport/task
@@ -27,6 +27,11 @@ pushd release-repo
   NEW_VERSION=$(join_by . "${split_version[@]}")
   commit_range="${old_tag}..HEAD"
 
+  if no_commits "${commit_range}"; then
+    echo "There are no commits... aborting"
+    exit 1
+  fi
+
   create_tagged_release "$NEW_VERSION"
   build_github_release_info "$RELEASE_NAME" "$NEW_VERSION" "${commit_range}" "$root_dir/github-release"
 popd
diff --git a/tasks/create-final-release/master/task b/tasks/create-final-release/master/task
--- a/tasks/create-final-release/master/task
+++ b/tasks/create-final-release/master/task
@@ -16,6 +16,11 @@ pushd master-repo
 
   old_tag=$(git describe --abbrev=0 --tags --match v* || git rev-list --max-parents=0 HEAD)
 
+  if no_commits "${old_tag}..HEAD"; then
+    echo "There are no commits... aborting"
+    exit 1
+  fi
+
   # this is needed to land commits on master since the commit for
   # master is checked out as a detatched head when the git
   # resource clones it down
