Add new metrics smoke test job
Signed-off-by: Max Eshleman <meshleman@pivotal.io>

diff --git a/pipelines/products.yml.erb b/pipelines/products.yml.erb
--- a/pipelines/products.yml.erb
+++ b/pipelines/products.yml.erb
@@ -36,6 +36,7 @@ groups:
   - cfar-lats
   - cats
   - lcats
+  - metrics-smoke-test
   - test-releases-can-be-exported
   - test-metrics-agent
   - upload-releases-to-dev-envs
@@ -501,6 +502,7 @@ jobs:
   - bosh-lcats
   - bosh-export-releases
   - bosh-metrics-agent
+  - bosh-metrics-test
   plan:
   - in_parallel:
     - get: loggregator-ci
@@ -660,6 +662,85 @@ jobs:
     params:
       BBL_STATE_DIR: ((acceptance_bbl_state_dir))
       METRICS_AGENT_PORT: 14826
+
+- name: metrics-smoke-test
+  serial: true
+#  serial_groups:
+#  - bosh-metrics-test
+  plan:
+  - in_parallel:
+    - get: loggregator-ci
+    - get: bbl-state
+      resource: deployments-loggregator
+    - get: cf-deployment-concourse-tasks-image
+    <% bosh_releases.each do |release| %>
+    - get: <%= release %>-release
+      trigger: true
+      passed: ["cf-deploy"]
+    <% end %>
+  - task: check-metrics
+    image: cf-deployment-concourse-tasks-image
+    config:
+      platform: linux
+      inputs:
+      - name: loggregator-ci
+      - name: bbl-state
+      <% bosh_releases.each do |release| %>
+      - name: <%= release %>-release
+        path: releases/<%= release %>-release
+      <% end %>
+      run:
+        path: /bin/bash
+        args:
+        - "-c"
+        - |
+          set -e
+          source loggregator-ci/scripts/environment-targeting/target-cf.sh
+          target-cf
+
+          log_meta_output=$(curl --silent log-cache.coconut.loggr.cf-app.com/api/v1/meta -H "Authorization: $(cf oauth-token)")
+
+          expected_source_ids=()
+          for j in releases/**/jobs/*; do
+            if [[ $j != *"windows"* ]] && [[ $j != *"fake"* ]]; then
+              expected_source_ids+=($(basename $j))
+            fi
+          done
+
+          exit_code=0
+          found_source_ids=()
+          missing_source_ids=()
+          five_minutes_ago_seconds=$(date --date '-5 min' +%s)
+
+          set +e
+          for source_id in ${expected_source_ids[@]}; do
+            source_id_last_emitted_seconds=$(echo ${log_meta_output} | jq -r '.meta["'${source_id}'"].newestTimestamp' | cut -b1-10)
+            if [[ ${source_id_last_emitted_seconds} -lt ${five_minutes_ago_seconds} ]]; then
+              exit_code=1
+              missing_source_ids+=(${source_id})
+            else
+              found_source_ids+=(${source_id})
+            fi
+          done
+
+          printf '\nFound metrics for the following source ids:\n'
+          printf '\t%s\n' "${found_source_ids[@]}"
+
+          printf '\nNo metrics were found for the following source ids:\n'
+          printf '\t%s\n' "${missing_source_ids[@]}"
+
+          exit ${exit_code}
+
+
+
+          loggregator_trafficcontroller -> traffic_controller
+
+      params:
+        CF_API: https://api.((acceptance_system_domain))
+        USERNAME: admin
+        ORG: system
+        SPACE: blackbox-testing
+        BBL_STATE_DIR: ((acceptance_bbl_state_dir))
 
 - name: cats
   serial: true
